# Generated by Django 6.0.2 on 2026-03-28 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("farmer", "Farmer"), ("buyer", "Buyer")],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("location_name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "farmer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small Scale Farmer"),
                            ("organic", "Organic Farmer"),
                            ("dairy", "Dairy Farmer"),
                            ("grain", "Grain Farmer"),
                            ("vegetable", "Vegetable Farmer"),
                            ("fruit", "Fruit Farmer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
