# Generated by Django 6.0.2 on 2026-03-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_userprofile_bank_upi_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.FileField(blank=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.FileField(blank=True, upload_to="profiles/"),
        ),
    ]
